title: Cachetool
description: Manage your caches through the cli
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions

analytics:
  provider: "google-gtag"
  google:
    measurement_id: "G-88T05SDN7N"
